apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: db
  name: db
  namespace: mktdigital-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom: 
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-secrets
            - name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secrets
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  key: MYSQL_RANDOM_ROOT_PASSWORD
                  name: mysql-secrets
            - name: MYSQL_USER
              valueFrom: 
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-secrets
          image: mysql:5.7
          name: db
          resources: {}
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
status: {}
