apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db
  name: db
  namespace: default
spec:
  ports:
    - name: "3306"
      port: 3306
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
