apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
  namespace: mktdigital-wordpress
spec:
  ports:
    - name: "3306"
      port: 3306
  selector:
    service: db
status:
  loadBalancer: {}
