apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: wordpress
  name: wordpress
  namespace: mktdigital-wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      service: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: wordpress
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              valueFrom: 
                secretKeyRef:
                  key: MYSQL_HOST
                  name: mysql-secrets
            - name: WORDPRESS_DB_NAME
              valueFrom: 
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-secrets
            - name: WORDPRESS_DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secrets
            - name: WORDPRESS_DB_USER
              valueFrom: 
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-secrets
          image: wordpress
          name: wordpress
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 2G
            requests:
              cpu: 1
              memory: 1G
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress
      restartPolicy: Always
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: wordpress
status: {}
