apiVersion: v1
kind: Service
metadata:
  labels:
    service: wordpress
  name: wordpress
  namespace: mktdigital-wordpress
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    service: wordpress
status:
  loadBalancer: {}
